import { boolean, date, integer, pgTable, serial, text, timestamp, unique } from 'drizzle-orm/pg-core'
export const users=pgTable('user',{id:text('id').primaryKey(),name:text('name').notNull(),email:text('email').notNull().unique(),emailVerified:boolean('emailVerified').notNull().default(false),image:text('image'),createdAt:timestamp('createdAt').notNull().defaultNow(),updatedAt:timestamp('updatedAt').notNull().defaultNow()})
export const schoolProfiles=pgTable('school_profiles',{id:serial('id').primaryKey(),userId:text('userId').notNull().unique(),schoolId:text('schoolId').notNull().default('selam-academy'),role:text('role').notNull().default('teacher')})
export const students=pgTable('students',{id:serial('id').primaryKey(),userId:text('userId').notNull(),schoolId:text('schoolId').notNull(),admissionNo:text('admissionNo').notNull(),firstName:text('firstName').notNull(),lastName:text('lastName').notNull(),firstNameAm:text('firstNameAm'),lastNameAm:text('lastNameAm'),gender:text('gender').notNull(),dateOfBirth:date('dateOfBirth').notNull(),grade:text('grade').notNull(),section:text('section').notNull(),guardianName:text('guardianName').notNull(),guardianPhone:text('guardianPhone').notNull(),status:text('status').notNull().default('active'),createdAt:timestamp('createdAt').notNull().defaultNow()})
export const teachers=pgTable('teachers',{id:serial('id').primaryKey(),userId:text('userId').notNull(),firstName:text('firstName').notNull(),lastName:text('lastName').notNull(),subject:text('subject').notNull(),employeeNo:text('employeeNo').notNull(),phone:text('phone').notNull(),email:text('email').notNull(),createdAt:timestamp('createdAt').notNull().defaultNow()})
export const announcements=pgTable('announcements',{id:serial('id').primaryKey(),userId:text('userId').notNull(),schoolId:text('schoolId').notNull(),titleEn:text('titleEn').notNull(),titleAm:text('titleAm').notNull(),bodyEn:text('bodyEn').notNull(),bodyAm:text('bodyAm').notNull(),audience:text('audience').notNull(),createdAt:timestamp('createdAt').notNull().defaultNow()})
export const attendance=pgTable('attendance',{id:serial('id').primaryKey(),userId:text('userId').notNull(),studentId:integer('studentId').notNull(),date:date('date').notNull(),status:text('status').notNull()},t=>[unique().on(t.userId,t.studentId,t.date)])
export const grades=pgTable('grades',{id:serial('id').primaryKey(),userId:text('userId').notNull(),studentId:integer('studentId').notNull(),subject:text('subject').notNull(),term:text('term').notNull(),assessment:text('assessment').notNull(),score:integer('score').notNull(),maxScore:integer('maxScore').notNull()})
export const fees=pgTable('fees',{id:serial('id').primaryKey(),userId:text('userId').notNull(),studentId:integer('studentId').notNull(),term:text('term').notNull(),amount:integer('amount').notNull(),paid:integer('paid').notNull(),dueDate:date('dueDate').notNull(),status:text('status').notNull()})
