import { boolean, date, integer, pgTable, serial, text, timestamp, unique } from 'drizzle-orm/pg-core'

export const user = pgTable('user', { id: text('id').primaryKey(), name: text('name').notNull(), email: text('email').notNull().unique(), emailVerified: boolean('emailVerified').notNull().default(false), image: text('image'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const session = pgTable('session', { id: text('id').primaryKey(), expiresAt: timestamp('expiresAt').notNull(), token: text('token').notNull().unique(), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow(), ipAddress: text('ipAddress'), userAgent: text('userAgent'), userId: text('userId').notNull().references(() => user.id, { onDelete: 'cascade' }) })
export const account = pgTable('account', { id: text('id').primaryKey(), accountId: text('accountId').notNull(), providerId: text('providerId').notNull(), userId: text('userId').notNull().references(() => user.id, { onDelete: 'cascade' }), accessToken: text('accessToken'), refreshToken: text('refreshToken'), idToken: text('idToken'), accessTokenExpiresAt: timestamp('accessTokenExpiresAt'), refreshTokenExpiresAt: timestamp('refreshTokenExpiresAt'), scope: text('scope'), password: text('password'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const verification = pgTable('verification', { id: text('id').primaryKey(), identifier: text('identifier').notNull(), value: text('value').notNull(), expiresAt: timestamp('expiresAt').notNull(), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const schoolProfiles = pgTable('school_profiles', { id: serial('id').primaryKey(), userId: text('userId').notNull().unique(), schoolId: text('schoolId').notNull().default('selam-academy'), role: text('role').notNull().default('teacher'), employeeNo: text('employeeNo'), createdAt: timestamp('createdAt').notNull().defaultNow() })
export const students = pgTable('students', { id: serial('id').primaryKey(), userId: text('userId').notNull(), schoolId: text('schoolId').notNull().default('selam-academy'), admissionNo: text('admissionNo').notNull(), firstName: text('firstName').notNull(), lastName: text('lastName').notNull(), firstNameAm: text('firstNameAm'), lastNameAm: text('lastNameAm'), gender: text('gender').notNull(), dateOfBirth: date('dateOfBirth').notNull(), grade: text('grade').notNull(), section: text('section').notNull(), guardianName: text('guardianName').notNull(), guardianPhone: text('guardianPhone').notNull(), status: text('status').notNull().default('active'), createdAt: timestamp('createdAt').notNull().defaultNow() }, t => [unique().on(t.userId, t.admissionNo)])
export const teachers = pgTable('teachers', { id: serial('id').primaryKey(), userId: text('userId').notNull(), schoolId: text('schoolId').notNull().default('selam-academy'), employeeNo: text('employeeNo').notNull(), firstName: text('firstName').notNull(), lastName: text('lastName').notNull(), subject: text('subject').notNull(), phone: text('phone').notNull(), email: text('email').notNull(), status: text('status').notNull().default('active'), createdAt: timestamp('createdAt').notNull().defaultNow() }, t => [unique().on(t.userId, t.employeeNo)])
export const announcements = pgTable('announcements', { id: serial('id').primaryKey(), userId: text('userId').notNull(), schoolId: text('schoolId').notNull().default('selam-academy'), titleEn: text('titleEn').notNull(), titleAm: text('titleAm').notNull(), bodyEn: text('bodyEn').notNull(), bodyAm: text('bodyAm').notNull(), audience: text('audience').notNull().default('all'), published: boolean('published').notNull().default(true), createdAt: timestamp('createdAt').notNull().defaultNow() })
export const attendance = pgTable('attendance', { id: serial('id').primaryKey(), userId: text('userId').notNull(), studentId: integer('studentId').notNull(), date: date('date').notNull(), status: text('status').notNull().default('present'), createdAt: timestamp('createdAt').notNull().defaultNow() }, t => [unique().on(t.userId, t.studentId, t.date)])
export const grades = pgTable('grades', { id: serial('id').primaryKey(), userId: text('userId').notNull(), studentId: integer('studentId').notNull(), subject: text('subject').notNull(), term: text('term').notNull(), assessment: text('assessment').notNull(), score: integer('score').notNull(), maxScore: integer('maxScore').notNull().default(100), createdAt: timestamp('createdAt').notNull().defaultNow() })
export const fees = pgTable('fees', { id: serial('id').primaryKey(), userId: text('userId').notNull(), studentId: integer('studentId').notNull(), term: text('term').notNull(), amount: integer('amount').notNull(), paid: integer('paid').notNull().default(0), dueDate: date('dueDate').notNull(), status: text('status').notNull().default('pending'), createdAt: timestamp('createdAt').notNull().defaultNow() })
