'use client'
import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { authClient } from '@/lib/auth-client'
import { ArrowRight, BookOpen, Eye, EyeOff } from 'lucide-react'

export function AuthForm({ mode }:{ mode:'sign-in'|'sign-up' }) {
  const router=useRouter(); const [error,setError]=useState(''); const [loading,setLoading]=useState(false); const [show,setShow]=useState(false)
  async function submit(e:React.FormEvent<HTMLFormElement>) { e.preventDefault(); setLoading(true); setError(''); const data=new FormData(e.currentTarget); const email=String(data.get('email')); const password=String(data.get('password')); const result=mode==='sign-up' ? await authClient.signUp.email({email,password,name:String(data.get('name'))}) : await authClient.signIn.email({email,password}); if(result.error){setError(result.error.message || 'Unable to continue');setLoading(false);return} router.push('/');router.refresh() }
  return <main className="auth-page"><section className="auth-brand"><div className="brand-mark"><BookOpen size={24}/></div><div><strong>Selam Academy</strong><span>ሰላም አካዳሚ</span></div><div className="auth-message"><p>School Management System</p><h1>Learning today,<br/>leading tomorrow.</h1><span>ዛሬ ተምረን፣ ነገን እንመራለን።</span></div></section><section className="auth-panel"><div className="auth-card"><p className="eyebrow">SELAM ACADEMY · ADDIS ABABA</p><h2>{mode==='sign-in'?'Welcome back':'Create your account'}</h2><p className="muted">{mode==='sign-in'?'Sign in to manage your school day.':'Set up secure access for your school.'}</p><form onSubmit={submit}>{mode==='sign-up'&&<label>Full name<input name="name" required placeholder="Abebe Bekele"/></label>}<label>Email address<input name="email" type="email" required placeholder="admin@selamacademy.edu.et"/></label><label>Password<div className="password"><input name="password" type={show?'text':'password'} required minLength={8} placeholder="At least 8 characters"/><button type="button" onClick={()=>setShow(!show)} aria-label="Show password">{show?<EyeOff/>:<Eye/>}</button></div></label>{error&&<p className="error" role="alert">{error}</p>}<button className="primary wide" disabled={loading}>{loading?'Please wait…':mode==='sign-in'?'Sign in':'Create account'}<ArrowRight size={18}/></button></form><p className="auth-switch">{mode==='sign-in'?'New to Selam Academy?':'Already have an account?'} <a href={mode==='sign-in'?'/sign-up':'/sign-in'}>{mode==='sign-in'?'Create account':'Sign in'}</a></p></div></section></main>
}
