'use client'
import { useMemo, useState, useTransition } from 'react'
import { addAnnouncement, addStudent, updateAttendance } from '@/app/actions/school'
import { authClient } from '@/lib/auth-client'
import { copy, Language } from '@/lib/i18n'
import { dualDate } from '@/lib/dates'
import { Bell, BookOpen, CalendarDays, CheckCircle2, ChevronDown, ClipboardCheck, GraduationCap, LayoutDashboard, Menu, Megaphone, Plus, ReceiptText, Search, Settings, Users, X } from 'lucide-react'

type Data={students:any[];teachers:any[];announcements:any[];attendance:any[];grades:any[];fees:any[]}
const nav=[['dashboard',LayoutDashboard],['students',GraduationCap],['teachers',Users],['attendance',ClipboardCheck],['grades',BookOpen],['fees',ReceiptText],['announcements',Megaphone]] as const
export function SchoolApp({data,user}:{data:Data;user:{name:string;email:string}}){
 const [lang,setLang]=useState<Language>('en'),[page,setPage]=useState('dashboard'),[menu,setMenu]=useState(false),[modal,setModal]=useState(''),[pending,start]=useTransition(); const t=copy[lang]
 const paid=data.fees.reduce((a,f)=>a+f.paid,0), total=data.fees.reduce((a,f)=>a+f.amount,0); const today=new Date(); const dates=dualDate(today)
 function run(action:()=>Promise<void>){start(async()=>{await action();setModal('')})}
 return <div className="app-shell"><aside className={menu?'sidebar open':'sidebar'}><div className="school-brand"><span><BookOpen/></span><div><strong>Selam Academy</strong><small>ሰላም አካዳሚ</small></div><button className="mobile-close" onClick={()=>setMenu(false)}><X/></button></div><div className="school-year"><small>{t.academicYear}</small><strong>2018 E.C. / 2025–26</strong></div><nav>{nav.map(([key,Icon])=><button key={key} className={page===key?'active':''} onClick={()=>{setPage(key);setMenu(false)}}><Icon/>{(t as any)[key]}</button>)}</nav><div className="sidebar-bottom"><button><Settings/>Settings</button><div className="user-mini"><span>{user.name.slice(0,2).toUpperCase()}</span><div><strong>{user.name}</strong><small>School administrator</small></div><ChevronDown/></div></div></aside><main className="workspace"><header className="topbar"><button className="menu-btn" onClick={()=>setMenu(true)}><Menu/></button><div className="search"><Search/><input placeholder={t.search}/><kbd>⌘ K</kbd></div><div className="top-actions"><button className="language" onClick={()=>setLang(lang==='en'?'am':'en')}>{lang==='en'?'አማ':'EN'}</button><button className="icon-btn"><Bell/><i/></button><button className="avatar" onClick={()=>authClient.signOut().then(()=>location.href='/sign-in')}>{user.name.slice(0,2).toUpperCase()}</button></div></header><div className="content">{page==='dashboard'&&<Dashboard/>}{page==='students'&&<Students/>}{page==='teachers'&&<Teachers/>}{page==='attendance'&&<Attendance/>}{page==='grades'&&<Grades/>}{page==='fees'&&<Fees/>}{page==='announcements'&&<Announcements/>}</div></main>{modal&&<Modal/>}</div>
 function Heading({title,sub,action}:{title:string;sub:string;action?:React.ReactNode}){return <div className="page-heading"><div><p>{dates.ethiopian} · {dates.gregorian}</p><h1>{title}</h1><span>{sub}</span></div>{action}</div>}
 function Dashboard(){const present=data.attendance.filter(a=>a.status==='present').length;return <><Heading title={`${t.welcome}, ${user.name.split(' ')[0]}`} sub={t.overview} action={<button className="primary" onClick={()=>setModal('student')}><Plus/>{t.addStudent}</button>}/><section className="metrics"><Metric icon={<GraduationCap/>} label={t.totalStudents} value={String(data.students.length)} note="K–12 · 24 sections"/><Metric icon={<Users/>} label={t.staff} value={String(data.teachers.length)} note="8 departments"/><Metric icon={<ClipboardCheck/>} label={t.attendanceToday} value={data.students.length?`${Math.round(present/data.students.length*100)}%`:'—'} note="Updated today"/><Metric icon={<ReceiptText/>} label={t.feeCollection} value={`${paid.toLocaleString()} Br`} note={total?`${Math.round(paid/total*100)}% collected`:'No invoices yet'}/></section><section className="dashboard-grid"><div className="card attendance-chart"><CardTitle title="Weekly attendance" action="This week"/><div className="chart-bars">{[89,94,91,96,93].map((n,i)=><div key={i}><span style={{height:`${n}%`}}/><small>{['Mon','Tue','Wed','Thu','Fri'][i]}</small></div>)}</div><div className="chart-foot"><strong>93.2%</strong><span>Average attendance · <b>+1.8%</b> from last week</span></div></div><div className="card"><CardTitle title={t.quickActions}/><div className="quick-grid"><button onClick={()=>setModal('student')}><GraduationCap/>Add student</button><button onClick={()=>setPage('attendance')}><ClipboardCheck/>Take attendance</button><button onClick={()=>setPage('grades')}><BookOpen/>Enter grades</button><button onClick={()=>setModal('notice')}><Megaphone/>Post notice</button></div></div><div className="card recent"><CardTitle title={t.recentStudents} action={t.viewAll}/>{data.students.length?data.students.slice(0,4).map(s=><StudentRow key={s.id} s={s}/>):<Empty text="No students enrolled yet"/>}</div><div className="card notices"><CardTitle title={t.announcements} action={t.viewAll}/>{data.announcements.length?data.announcements.slice(0,3).map(n=><div className="notice" key={n.id}><span><Megaphone/></span><div><strong>{lang==='en'?n.titleEn:n.titleAm}</strong><p>{lang==='en'?n.bodyEn:n.bodyAm}</p><small>{dualDate(n.createdAt).ethiopian}</small></div></div>):<Empty text="No announcements yet"/>}</div></section></>}
 function Students(){return <><Heading title={t.students} sub={`${data.students.length} enrolled learners across K–12`} action={<button className="primary" onClick={()=>setModal('student')}><Plus/>{t.addStudent}</button>}/><div className="card table-card"><div className="filters"><div className="search mini"><Search/><input placeholder="Search roster"/></div><button>All grades <ChevronDown/></button><button>Active <ChevronDown/></button></div><table><thead><tr><th>Student</th><th>Admission no.</th><th>Grade</th><th>Guardian</th><th>Status</th></tr></thead><tbody>{data.students.map(s=><tr key={s.id}><td><StudentName s={s}/></td><td>{s.admissionNo}</td><td>Grade {s.grade} · {s.section}</td><td>{s.guardianName}<small>{s.guardianPhone}</small></td><td><b className="status active">{t.active}</b></td></tr>)}</tbody></table>{!data.students.length&&<Empty text="Add your first student to begin building the roster."/>}</div></>}
 function Teachers(){return <><Heading title={t.teachers} sub={`${data.teachers.length} teaching staff in 8 departments`} action={<button className="primary"><Plus/>Add teacher</button>}/><div className="staff-grid">{data.teachers.length?data.teachers.map(x=><div className="card staff-card" key={x.id}><span className="large-avatar">{x.firstName[0]}{x.lastName[0]}</span><h3>{x.firstName} {x.lastName}</h3><p>{x.subject}</p><small>{x.employeeNo} · {x.phone}</small></div>):<div className="card"><Empty text="Teacher records will appear here."/></div>}</div></>}
 function Attendance(){return <><Heading title={t.attendance} sub="Daily register · Grade and section view"/><div className="card register"><div className="filters"><button><CalendarDays/> {dates.gregorian}</button><button>All grades <ChevronDown/></button></div>{data.students.map(s=><div className="register-row" key={s.id}><StudentName s={s}/><div>{['present','absent','late'].map(status=><button key={status} className={data.attendance.find(a=>a.studentId===s.id)?.status===status?'selected '+status:''} onClick={()=>run(()=>updateAttendance(s.id,status))}>{(t as any)[status]}</button>)}</div></div>)}{!data.students.length&&<Empty text="Enroll students before taking attendance."/>}</div></>}
 function Grades(){return <><Heading title={t.grades} sub="Term assessments and student performance"/><div className="metrics"><Metric icon={<BookOpen/>} label="School average" value={data.grades.length?`${Math.round(data.grades.reduce((a,g)=>a+g.score/g.maxScore*100,0)/data.grades.length)}%`:'—'} note="Term 2"/><Metric icon={<CheckCircle2/>} label="Assessments entered" value={String(data.grades.length)} note="Across all subjects"/></div><div className="card"><Empty text="Select a class and assessment to enter grades."/></div></>}
 function Fees(){return <><Heading title={t.fees} sub="Invoices, payments and outstanding balances"/><section className="metrics"><Metric icon={<ReceiptText/>} label="Total invoiced" value={`${total.toLocaleString()} Br`} note="Current academic year"/><Metric icon={<CheckCircle2/>} label="Collected" value={`${paid.toLocaleString()} Br`} note={total?`${Math.round(paid/total*100)}% of invoiced`:'No invoices'}/></section><div className="card"><Empty text="Fee invoices and payment history will appear here."/></div></>}
 function Announcements(){return <><Heading title={t.announcements} sub="Bilingual notices for the school community" action={<button className="primary" onClick={()=>setModal('notice')}><Plus/>{t.newNotice}</button>}/><div className="notice-list">{data.announcements.map(n=><article className="card" key={n.id}><div className="notice-head"><b>{n.audience}</b><small>{dualDate(n.createdAt).gregorian}<br/>{dualDate(n.createdAt).ethiopian}</small></div><h3>{lang==='en'?n.titleEn:n.titleAm}</h3><p>{lang==='en'?n.bodyEn:n.bodyAm}</p></article>)}{!data.announcements.length&&<div className="card"><Empty text="Publish your first school announcement."/></div>}</div></>}
 function Modal(){if(modal==='student')return <div className="modal-backdrop"><div className="modal"><button className="modal-x" onClick={()=>setModal('')}><X/></button><p className="eyebrow">NEW ENROLLMENT</p><h2>Add student</h2><form action={fd=>run(()=>addStudent(fd))} className="form-grid"><label>First name<input name="firstName" required/></label><label>Last name<input name="lastName" required/></label><label>ስም<input name="firstNameAm"/></label><label>የአባት ስም<input name="lastNameAm"/></label><label>Admission no.<input name="admissionNo" required placeholder="SA-2018-001"/></label><label>Date of birth<input name="dateOfBirth" type="date" required/></label><label>Gender<select name="gender"><option>Female</option><option>Male</option></select></label><label>Grade<select name="grade">{Array.from({length:13},(_,i)=><option key={i} value={i}>{i===0?'KG':`Grade ${i}`}</option>)}</select></label><label>Section<input name="section" required placeholder="A"/></label><label>Guardian name<input name="guardianName" required/></label><label className="span-2">Guardian phone<input name="guardianPhone" required placeholder="+251 9..."/></label><div className="form-actions span-2"><button type="button" onClick={()=>setModal('')}>Cancel</button><button className="primary" disabled={pending}>Save student</button></div></form></div></div>;return <div className="modal-backdrop"><div className="modal"><button className="modal-x" onClick={()=>setModal('')}><X/></button><p className="eyebrow">COMMUNICATION</p><h2>New announcement</h2><form action={fd=>run(()=>addAnnouncement(fd))} className="form-grid"><label className="span-2">English title<input name="titleEn" required/></label><label className="span-2">Amharic title<input name="titleAm" required/></label><label className="span-2">English message<textarea name="bodyEn" required/></label><label className="span-2">Amharic message<textarea name="bodyAm" required/></label><label>Audience<select name="audience"><option value="all">Everyone</option><option value="teachers">Teachers</option><option value="parents">Parents</option></select></label><div className="form-actions span-2"><button type="button" onClick={()=>setModal('')}>Cancel</button><button className="primary" disabled={pending}>Publish</button></div></form></div></div>}
}
function Metric({icon,label,value,note}:{icon:React.ReactNode;label:string;value:string;note:string}){return <div className="metric card"><span>{icon}</span><div><p>{label}</p><strong>{value}</strong><small>{note}</small></div></div>}
function CardTitle({title,action}:{title:string;action?:string}){return <div className="card-title"><h2>{title}</h2>{action&&<button>{action}<ChevronDown/></button>}</div>}
function StudentName({s}:{s:any}){return <div className="student-name"><span>{s.firstName[0]}{s.lastName[0]}</span><div><strong>{s.firstName} {s.lastName}</strong><small>{s.firstNameAm} {s.lastNameAm}</small></div></div>}
function StudentRow({s}:{s:any}){return <div className="student-row"><StudentName s={s}/><span>Grade {s.grade} · {s.section}</span><b className="status active">Active</b></div>}
function Empty({text}:{text:string}){return <div className="empty"><BookOpen/><strong>{text}</strong><p>Your school data is securely stored in Neon.</p></div>}
